name: build_release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CUSTOM_GITHUB_PAT }}
          submodules: true
      - name: Build image
        if: success()
        run: |
          docker build \
              -f Dockerfile \
              .
      - name: Build and push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
      - name: Build and push to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
          registry: quay.io
          tag_names: true
